bump

diff --git a/.github/workflows/Pull.yml b/.github/workflows/Pull.yml
--- a/.github/workflows/Pull.yml
+++ b/.github/workflows/Pull.yml
@@ -29,10 +29,18 @@ jobs:
           LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
         run: |
           chmod +x .github/scripts/lokalise_download.sh
+          echo "Running lokalise_download.sh script..."
+          
+          # Capture the exit code and output
+          ./.github/scripts/lokalise_download.sh "$LOKALISE_PROJECT_ID"
+          exit_code=$?
 
-          if ! ./.github/scripts/lokalise_download.sh "$LOKALISE_PROJECT_ID"; then
+          echo "Script exited with code: $exit_code"
+
+          # Process based on the exit code
+          if [ $exit_code -ne 0 ]; then
             echo "Error during file download"
-            exit 1
+            exit $exit_code
           fi
 
           if [[ -z $(git status --untracked-files=no --porcelain) ]]; then
