fixes

diff --git a/.github/workflows/Pull.yml b/.github/workflows/Pull.yml
--- a/.github/workflows/Pull.yml
+++ b/.github/workflows/Pull.yml
@@ -32,18 +32,12 @@ jobs:
             local attempt=0
             local max_retries=3
             local sleep_time=1
+            local additional_params="${LOKALISE_CLI_ADD_PARAMS:-}"
 
             while [ $attempt -lt $max_retries ]; do
               echo "Attempt $((attempt + 1)) of $max_retries"
 
               set +e  # Temporarily disable exit on error
-
-              # Check if LOKALISE_CLI_ADD_PARAMS is set and not empty
-              if [ -n "${LOKALISE_CLI_ADD_PARAMS}" ]; then
-                additional_params="${LOKALISE_CLI_ADD_PARAMS}"
-              else
-                additional_params=""
-              fi
 
               # Run the lokalise2 command and capture the output
               output=$(./bin/lokalise2 --token="${LOKALISE_API_TOKEN}" \
@@ -61,23 +55,19 @@ jobs:
 
               set -e  # Re-enable exit on error
 
-              # Process the output
-              if [ $exit_code -ne 0 ]; then
-                if echo "$output" | grep -q 'API request error 429'; then
-                  attempt=$((attempt + 1))
-                  echo "Attempt $attempt failed with API request error 429. Retrying in $sleep_time seconds..."
-                  sleep $sleep_time
-                  sleep_time=$((sleep_time * 2))
-                elif echo "$output" | grep -q 'API request error'; then
-                  echo "Permanent error encountered during download: $output"
-                  return 1
-                else
-                  echo "Unexpected error occurred: $output"
-                  return 1
-                fi
-              else
+              if [ $exit_code -eq 0 ]; then
                 echo "Successfully downloaded files"
                 return 0
+              fi
+
+              if echo "$output" | grep -q 'API request error 429'; then
+                attempt=$((attempt + 1))
+                echo "Attempt $attempt failed with API request error 429. Retrying in $sleep_time seconds..."
+                sleep $sleep_time
+                sleep_time=$((sleep_time * 2))
+              else
+                echo "Error encountered during download: $output"
+                return 1
               fi
             done
 
@@ -85,11 +75,9 @@ jobs:
             return 1
           }
 
-          download_files
-          result=$?
-          if [ $result -ne 0 ]; then
-            echo "Error during file download with exit code $result"
-            exit $result
+          if ! download_files; then
+            echo "Error during file download"
+            exit 1
           fi
 
           if [[ -z $(git status --untracked-files=no --porcelain) ]]; then
diff --git a/.github/workflows/PullBranches.yml b/.github/workflows/PullBranches.yml
--- a/.github/workflows/PullBranches.yml
+++ b/.github/workflows/PullBranches.yml
@@ -14,7 +14,7 @@ jobs:
       - name: Checkout Repo
         uses: actions/checkout@v4
         with:
-          fetch-depth: 0  # Fetch the full history of the repository to ensure all commits are available
+          fetch-depth: 0
 
       - name: Install Lokalise CLI
         run: |
@@ -53,18 +53,12 @@ jobs:
             local attempt=0
             local max_retries=3
             local sleep_time=1
+            local additional_params="${LOKALISE_CLI_ADD_PARAMS:-}"
 
             while [ $attempt -lt $max_retries ]; do
               echo "Attempt $((attempt + 1)) of $max_retries"
 
               set +e  # Temporarily disable exit on error
-
-              # Check if LOKALISE_CLI_ADD_PARAMS is set and not empty
-              if [ -n "${LOKALISE_CLI_ADD_PARAMS}" ]; then
-                additional_params="${LOKALISE_CLI_ADD_PARAMS}"
-              else
-                additional_params=""
-              fi
 
               # Run the lokalise2 command and capture the output
               output=$(./bin/lokalise2 --token="${LOKALISE_API_TOKEN}" \
@@ -83,22 +77,17 @@ jobs:
               set -e  # Re-enable exit on error
 
               # Process the output
-              if [ $exit_code -ne 0 ]; then
-                if echo "$output" | grep -q 'API request error 429'; then
-                  attempt=$((attempt + 1))
-                  echo "Attempt $attempt failed with API request error 429. Retrying in $sleep_time seconds..."
-                  sleep $sleep_time
-                  sleep_time=$((sleep_time * 2))
-                elif echo "$output" | grep -q 'API request error'; then
-                  echo "Permanent error encountered during download: $output"
-                  return 1
-                else
-                  echo "Unexpected error occurred: $output"
-                  return 1
-                fi
-              else
+              if [ $exit_code -eq 0 ]; then
                 echo "Successfully downloaded files"
                 return 0
+              elif echo "$output" | grep -q 'API request error 429'; then
+                attempt=$((attempt + 1))
+                echo "Attempt $attempt failed with API request error 429. Retrying in $sleep_time seconds..."
+                sleep $sleep_time
+                sleep_time=$((sleep_time * 2))
+              else
+                echo "Error encountered during download: $output"
+                return 1
               fi
             done
 
@@ -106,21 +95,14 @@ jobs:
             return 1
           }
 
-          download_files
-          result=$?
-          if [ $result -ne 0 ]; then
-            echo "Error during file download with exit code $result"
-            exit $result
+          if ! download_files; then
+            echo "Error during file download"
+            exit 1
           fi
 
-          git status
-
-          echo "Checking for unstaged changes..."
           if [[ -n $(git status --untracked-files=no --porcelain) ]]; then
-            echo "Changes detected."
             echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
           else
-            echo "No changes detected."
             echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
           fi
 
@@ -139,21 +121,12 @@ jobs:
           git config --global user.name "${GITHUB_ACTOR}"
           git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
 
-          if git show-ref --quiet refs/heads/"$GIT_LOCALIZATION_BRANCH_NAME"; then
-            echo "Git Branch $GIT_LOCALIZATION_BRANCH_NAME already exists. Checking out the branch."
-            git checkout "$GIT_LOCALIZATION_BRANCH_NAME"
-          else
-            echo "Branch $GIT_LOCALIZATION_BRANCH_NAME does not exist. Creating and checking out the branch."
-            git checkout -b "$GIT_LOCALIZATION_BRANCH_NAME"
-          fi
+          git checkout -b "$GIT_LOCALIZATION_BRANCH_NAME" || git checkout "$GIT_LOCALIZATION_BRANCH_NAME"
 
-          echo "Adding files to staging area:"
           git add "${{ env.LOKALISE_FOLDER_PATH }}/**/*.${{ env.LOKALISE_FILE_FORMAT }}" -- ':!${{ env.LOKALISE_FOLDER_PATH }}/${{ env.LOKALISE_SOURCE_LANG_ISO }}/*.${{ env.LOKALISE_FILE_FORMAT }}'
 
-          echo "Committing changes..."
           git commit -m 'Translations update'
 
-          echo "Pushing changes to remote repository..."
           git push origin "$GIT_LOCALIZATION_BRANCH_NAME"
 
       - name: Create Pull Request if changes detected
@@ -162,13 +135,11 @@ jobs:
           GH_TOKEN: ${{ github.token }}
         run: |
           gh pr create --base "${{ github.ref_name }}" \
-                      --head "$GIT_LOCALIZATION_BRANCH_NAME" \
-                      --title "Lokalise translations update" \
-                      --body ""
-
-          if [ $? -eq 0 ]; then
-            echo "Pull Request created successfully."
-          else
+                       --head "$GIT_LOCALIZATION_BRANCH_NAME" \
+                       --title "Lokalise translations update" \
+                       --body "" || {
             echo "Failed to create Pull Request."
             exit 1
-          fi
+          }
+
+          echo "Pull Request created successfully."
diff --git a/.github/workflows/Push.yml b/.github/workflows/Push.yml
--- a/.github/workflows/Push.yml
+++ b/.github/workflows/Push.yml
@@ -2,9 +2,6 @@ name: Push to Lokalise
 run-name: Push to Lokalise [${{ github.ref_name }}] ${{ github.event.after }}
 on:
   workflow_dispatch:
-  # Uncomment to run on PR merge:
-  # pull_request_target:
-  #   types: [closed]
 
 jobs:
   build:
@@ -51,13 +48,7 @@ jobs:
             local attempt=0
             local max_retries=3
             local sleep_time=1
-
-            # Check if LOKALISE_CLI_ADD_PARAMS is set and not empty
-            if [ -n "${LOKALISE_CLI_ADD_PARAMS}" ]; then
-              additional_params="${LOKALISE_CLI_ADD_PARAMS}"
-            else
-              additional_params=""
-            fi
+            local additional_params="${LOKALISE_CLI_ADD_PARAMS:-}"
 
             echo "Starting upload for $file"
             while [ $attempt -lt $max_retries ]; do
@@ -77,17 +68,17 @@ jobs:
                 --tags "$GITHUB_REF_NAME" \
                 $additional_params 2>&1)
 
-              if echo "$output" | grep -q 'API request error 429'; then
+              if [ $? -eq 0 ]; then
+                echo "Successfully uploaded file: $file"
+                return 0
+              elif echo "$output" | grep -q 'API request error 429'; then
                 attempt=$((attempt + 1))
                 echo "Attempt $attempt failed with API request error 429. Retrying in $sleep_time seconds..."
                 sleep $sleep_time
                 sleep_time=$((sleep_time * 2))
-              elif echo "$output" | grep -q 'API request error'; then
+              else
                 echo "Permanent error encountered during upload: $output"
                 return 1
-              else
-                echo "Successfully uploaded file: $file"
-                return 0
               fi
             done
 
@@ -97,8 +88,7 @@ jobs:
 
           export -f upload_file
           echo "${ALL_CHANGED_FILES}" | tr ' ' '\n' | xargs -P 6 -I {} bash -c 'upload_file "$@"' _ {}
-          result=$?
-          if [ $result -ne 0 ]; then
-            echo "Error during file upload with exit code $result"
-            exit $result
+          if [ $? -ne 0 ]; then
+            echo "File upload failed"
+            exit 1
           fi
diff --git a/.github/workflows/PushBranches.yml b/.github/workflows/PushBranches.yml
--- a/.github/workflows/PushBranches.yml
+++ b/.github/workflows/PushBranches.yml
@@ -23,11 +23,9 @@ jobs:
       - name: Check if Triggering Branch is Default Branch
         run: |
           if [ "${{ github.ref_name }}" = "${{ github.event.repository.default_branch }}" ]; then
-            echo "The Git default branch triggered this workflow."
             echo "LOKALISE_BRANCH=master" >> $GITHUB_ENV
             echo "IS_DEFAULT_BRANCH=true" >> $GITHUB_ENV
           else
-            echo "A Git feature branch triggered this workflow."
             echo "LOKALISE_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
             echo "IS_DEFAULT_BRANCH=false" >> $GITHUB_ENV
           fi
@@ -39,7 +37,7 @@ jobs:
           CURRENT_SHA="${{ github.sha }}"
 
           if [ "$BASE_SHA" = "$CURRENT_SHA" ]; then
-            echo "Identical commit hashes detected for base and current SHA. No changes detected."
+            echo "No changes detected between the base and current SHA."
             echo "SKIP_CHANGED_FILES_STEP=true" >> $GITHUB_ENV
             exit 0
           else
@@ -74,34 +72,21 @@ jobs:
         if: ${{ env.IS_DEFAULT_BRANCH == 'false' && steps.changed-files.outputs.any_changed == 'true' }}
         run: |
           LOKALISE_BRANCHES=$(./bin/lokalise2 --token="${{ env.LOKALISE_API_TOKEN }}" \
-            --project-id="${{ env.LOKALISE_PROJECT_ID }}" \
-            branch list)
+            --project-id="${{ env.LOKALISE_PROJECT_ID }}" branch list | jq -r '.branches[].name')
 
-          if echo "$LOKALISE_BRANCHES" | grep -q "API request error"; then
-            echo "Error: Failed to retrieve branches from Lokalise. Exiting."
-            exit 1
-          fi
-
-          LOKALISE_BRANCHES=$(echo "$LOKALISE_BRANCHES" | jq -r '.branches[].name')
-
-          if echo "$LOKALISE_BRANCHES" | grep -qw "${{ github.ref_name }}"; then
-            echo "Branch '${{ github.ref_name }}' exists in Lokalise. Continuing on Lokalise branch."
-            LOKALISE_BRANCH="${{ github.ref_name }}"
+          if echo "$LOKALISE_BRANCHES" | grep -qw "${{ env.LOKALISE_BRANCH }}"; then
+            echo "Branch '${{ env.LOKALISE_BRANCH }}' exists in Lokalise."
           else
-            echo "Branch '${{ github.ref_name }}' does not exist in Lokalise. Creating a new branch in Lokalise."
-            LOKALISE_BRANCH="${{ github.ref_name }}"
-
-            RESPONSE=$(./bin/lokalise2 --token="${{ env.LOKALISE_API_TOKEN }}" \
+            echo "Branch '${{ env.LOKALISE_BRANCH }}' does not exist. Creating it now."
+            
+            ./bin/lokalise2 --token="${{ env.LOKALISE_API_TOKEN }}" \
               --project-id="${{ env.LOKALISE_PROJECT_ID }}" \
-              branch create \
-              --name "$LOKALISE_BRANCH")
-
-            if echo "$RESPONSE" | grep -q "API request error"; then
-              echo "Error: Failed to create branch in Lokalise."
-              exit 1
-            else
-              echo "Branch created successfully in Lokalise."
-            fi
+              branch create --name "${{ env.LOKALISE_BRANCH }}" || {
+                echo "Failed to create branch in Lokalise."
+                exit 1
+              }
+            
+            echo "Branch '${{ env.LOKALISE_BRANCH }}' created successfully."
           fi
 
           echo "LOKALISE_BRANCH=$LOKALISE_BRANCH" >> $GITHUB_ENV
@@ -116,8 +101,7 @@ jobs:
             localization_files=$(find "${{ env.LOKALISE_TRANSLATIONS_PATH }}/${{ env.LOKALISE_SOURCE_LANG_ISO }}" -type f -name "*.${{ env.LOKALISE_FILE_FORMAT }}")
           else
             PROJECT_ID_WITH_BRANCH="${{ env.LOKALISE_PROJECT_ID }}:${{ env.LOKALISE_BRANCH }}"
-            localization_files="${{ steps.changed-files.outputs.all_changed_files }}"
-            localization_files=$(echo "$localization_files" | tr ' ' '\n')
+            localization_files=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n')
           fi
 
           if [ -z "$localization_files" ]; then
@@ -132,13 +116,8 @@ jobs:
             local attempt=0
             local max_retries=3
             local sleep_time=1
-
-            if [ -n "${LOKALISE_CLI_ADD_PARAMS}" ]; then
-              additional_params="${LOKALISE_CLI_ADD_PARAMS}"
-            else
-              additional_params=""
-            fi
-
+            local additional_params="${LOKALISE_CLI_ADD_PARAMS:-}"
+            
             echo "Starting upload for $file"
             while [ $attempt -lt $max_retries ]; do
               output=$(./bin/lokalise2 --token="${LOKALISE_API_TOKEN}" \
@@ -157,17 +136,17 @@ jobs:
                 --tags "$GITHUB_REF_NAME" \
                 $additional_params 2>&1)
 
-              if echo "$output" | grep -q 'API request error 429'; then
+              if [ $? -eq 0 ]; then
+                echo "Successfully uploaded $file"
+                return 0
+              elif echo "$output" | grep -q 'API request error 429'; then
                 attempt=$((attempt + 1))
                 echo "Attempt $attempt failed with API request error 429. Retrying in $sleep_time seconds..."
                 sleep $sleep_time
                 sleep_time=$((sleep_time * 2))
-              elif echo "$output" | grep -q 'API request error'; then
-                echo "Permanent error encountered during upload: $output"
-                return 1
               else
-                echo "Successfully uploaded file: $file"
-                return 0
+                echo "Error: $output"
+                return 1
               fi
             done
 
@@ -178,8 +157,7 @@ jobs:
           export -f upload_file
 
           echo "$localization_files" | xargs -P 6 -I {} bash -c 'upload_file "$@"' _ {}
-          result=$?
-          if [ $result -ne 0 ]; then
-            echo "Error during file upload with exit code $result"
-            exit $result
+          if [ $? -ne 0 ]; then
+            echo "File upload failed"
+            exit 1
           fi
